### ISSUE TITLE
NPE after deleting single project with content from multi-project hg root

### ISSUE THREAD

**Issue by GoogleCodeExporter** [anterzhang/mercurialeclipse#14]
```
What steps will reproduce the problem?
1. Clone project wiki repo (3 projects)
2. Delete one of the projects and select "with content".
3. Observe error in the error log:

java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:922)
    at com.vectrace.MercurialEclipse.team.cache.MercurialStatusCache.setMergeStatus(MercurialStatusCache.java:1510)
    at com.vectrace.MercurialEclipse.team.cache.MercurialStatusCache.refreshStatus(MercurialStatusCache.java:728)
    at com.vectrace.MercurialEclipse.team.cache.RefreshRootJob.run(RefreshRootJob.java:92)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)



```

Original issue reported on code.google.com by `iloveeclipse` on 27 Nov 2010 at 7:22

**Comment by GoogleCodeExporter** [comment]
Original comment by `iloveeclipse` on 27 Nov 2010 at 9:01
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `johnpeb@gmail.com` on 6 Dec 2010 at 12:20
- Added labels: **Milestone-Release1.7.1**
