### ISSUE TITLE
NPE while switching history view layout

### ISSUE THREAD

**Issue by GoogleCodeExporter** [anterzhang/mercurialeclipse#17]
```
What steps will reproduce the problem?
1. Open history on any hg file
2. Switch view layout to vertical.

Stack:

java.lang.NullPointerException
at 
com.vectrace.MercurialEclipse.history.ChangedPathsPage.disposeExistingViewers(Ch
angedPathsPage.java:218)
at 
com.vectrace.MercurialEclipse.history.ChangedPathsPage.createRevisionDetailViewe
rs(ChangedPathsPage.java:199)
at 
com.vectrace.MercurialEclipse.history.ChangedPathsPage.access$2(ChangedPathsPage
.java:198)
at 
com.vectrace.MercurialEclipse.history.ChangedPathsPage$ToggleAffectedPathsOption
Action.run(ChangedPathsPage.java:664)
at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
at 
org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionCont
ributionItem.java:584)
at 
org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.
java:501)
at 
org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContribution
Item.java:411)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1258)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3540)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3161)
at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2640)
at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2604)
at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2438)
at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:671)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:664)
at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
at 
org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java
:115)
at 
org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
at 
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(Ecli
pseAppLauncher.java:110)
at 
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLau
ncher.java:79)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:619)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:574)
at org.eclipse.equinox.launcher.Main.run(Main.java:1407)
at org.eclipse.equinox.launcher.Main.main(Main.java:1383)


```

Original issue reported on code.google.com by `iloveeclipse` on 27 Nov 2010 at 9:51

**Comment by GoogleCodeExporter** [comment]
Original comment by `iloveeclipse` on 27 Nov 2010 at 10:07
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `johnpeb@gmail.com` on 6 Dec 2010 at 12:20
- Added labels: **Milestone-Release1.7.1**
