### ISSUE TITLE
Current Release and Snapshot Version are broken with Eclipse Juno 4.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [anterzhang/mercurialeclipse#37]
```
Eclipse crashes at startup with following log message

!SESSION 2012-07-03 13:36:40.345 -----------------------------------------------
eclipse.buildId=I20120608-1400
java.version=1.7.0_05
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.reporting.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product 
org.eclipse.epp.package.reporting.product

!ENTRY org.eclipse.core.resources 2 10035 2012-07-03 13:36:45.906
!MESSAGE The workspace exited with unsaved changes in the previous session; 
refreshing workspace to recover changes.

!ENTRY com.vectrace.MercurialEclipse 4 0 2012-07-03 13:36:46.501
!MESSAGE Invalid thread access
!STACK 0
org.eclipse.swt.SWTError: Invalid thread access
        at org.eclipse.ui.plugin.AbstractUIPlugin.createImageRegistry(AbstractUIPlugin.java:212)
        at org.eclipse.ui.plugin.AbstractUIPlugin.getImageRegistry(AbstractUIPlugin.java:256)
        at com.vectrace.MercurialEclipse.MercurialEclipsePlugin.getImageDescriptor(MercurialEclipsePlugin.java:335)
        at com.vectrace.MercurialEclipse.views.console.HgConsole.<init>(HgConsole.java:77)
        at com.vectrace.MercurialEclipse.views.console.HgConsoleHolder.init(HgConsoleHolder.java:69)
        at com.vectrace.MercurialEclipse.views.console.HgConsoleHolder.getConsole(HgConsoleHolder.java:180)
        at com.vectrace.MercurialEclipse.DefaultConfiguration.commandInvoked(DefaultConfiguration.java:101)
        at com.vectrace.MercurialEclipse.commands.CommandJob.logConsoleCommandInvoked(CommandJob.java:128)
        at com.vectrace.MercurialEclipse.commands.CommandJob.execute(CommandJob.java:161)
        at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToStream(AbstractShellCommand.java:359)
        at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToBytes(AbstractShellCommand.java:339)
        at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToBytes(AbstractShellCommand.java:328)
        at com.vectrace.MercurialEclipse.commands.HgDebugInstallClient.debugInstall(HgDebugInstallClient.java:30)
        at com.vectrace.MercurialEclipse.MercurialEclipsePlugin.checkHgInstallation(MercurialEclipsePlugin.java:218)
        at com.vectrace.MercurialEclipse.MercurialEclipsePlugin$1.run(MercurialEclipsePlugin.java:155)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

```

Original issue reported on code.google.com by `mrExcept...@gmail.com` on 3 Jul 2012 at 11:39

**Comment by GoogleCodeExporter** [comment]
```
New snapshot coming soon
```

Original comment by `johnpeb@gmail.com` on 5 Jul 2012 at 4:54
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
I tested it with your latest snapshot containing the fix but it is still not 
working see attached file.
```

Original comment by `mrExcept...@gmail.com` on 5 Jul 2012 at 9:44

Attachments:
- [.log](https://storage.googleapis.com/google-code-attachments/mercurialeclipse/issue-37/comment-2/.log)

**Comment by GoogleCodeExporter** [comment]
```
I tried in 4.2 this time and wasn't able to reproduce again. From the stack 
trace it looks like a static intializer is doing something too early before the 
workbench plugin is ready. 

I've uploaded another snaphot but it's possible another issue will then be 
exposed. 




org.eclipse.swt.SWTException: Failed to execute runnable 
(java.lang.NullPointerException)
at org.eclipse.swt.SWT.error(SWT.java:4361)
at org.eclipse.swt.SWT.error(SWT.java:4276)
at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)
at org.eclipse.swt.widgets.Display.setSynchronizer(Display.java:3939)
at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2405)
at org.eclipse.ui.internal.Workbench.access$7(Workbench.java:2386)
at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:583)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:540)
at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
at 
org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java
:124)
at 
org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
at 
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(Ecli
pseAppLauncher.java:110)
at 
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLau
ncher.java:79)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:43)
at java.lang.reflect.Method.invoke(Method.java:601)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
Caused by: java.lang.NullPointerException
at 
org.eclipse.ui.internal.WorkbenchPlugin.getSharedImages(WorkbenchPlugin.java:648
)
at org.eclipse.ui.internal.Workbench.getSharedImages(Workbench.java:1315)
at 
org.eclipse.ui.plugin.AbstractUIPlugin.imageDescriptorFromPlugin(AbstractUIPlugi
n.java:670)
at 
com.vectrace.MercurialEclipse.MercurialEclipsePlugin.getImageDescriptor(Mercuria
lEclipsePlugin.java:323)
at 
com.vectrace.MercurialEclipse.commands.AbstractShellCommand$1.run(AbstractShellC
ommand.java:69)
at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
... 21 more


```

Original comment by `johnpeb@gmail.com` on 5 Jul 2012 at 1:00

**Comment by GoogleCodeExporter** [comment]
```
Issue 39 has been merged into this issue.
```

Original comment by `johnpeb@gmail.com` on 7 Jul 2012 at 4:36

**Comment by GoogleCodeExporter** [comment]
```
Issue 40 has been merged into this issue.
```

Original comment by `johnpeb@gmail.com` on 24 Jul 2012 at 1:01

**Comment by GoogleCodeExporter** [comment]
```
Issue 41 has been merged into this issue.
```

Original comment by `johnpeb@gmail.com` on 25 Jul 2012 at 2:28

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I have installed the snapshot and the problem appeared resolved until......
my windows crashed and I was forced to reboot with unsaved changes
as described.

The problem reoccurred and I was forced once again to temporarily remove
the jar from plugins in order to restart Eclipse Juno. Eclipse now works
but com.vectrace.MercurialEclipse_2.0.0.201207180102.jar is
not functioning. I will try a clean reinstall from Eclipse.

On Sun, Jul 29, 2012 at 5:22 PM, <
mercurialeclipse.eclipselabs.org@codespot.com> wrote:
```

Original comment by `ryanheit...@gmail.com` on 31 Jul 2012 at 3:13

**Comment by GoogleCodeExporter** [comment]
```
Can you post the stack trace you observed with Juno and the latest snapshot? It 
should be different to above. To get the stack trace please do Window -> Show 
View -> Other.. -> Error Log. Then hopefully there will be an error at the time 
the crash occurred.

Also please post any error you see now that MercurialEclipse is not functioning
```

Original comment by `johnpeb@gmail.com` on 31 Jul 2012 at 3:31

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I think those stack traces are referring to the 1.9.4 code. Can you delete the 
1.9.4 jars in both plugins and features, then it's probably safest to use the 
update site to install 2.0 (use the snaphot update site till 2.0 is released). 
```

Original comment by `johnpeb@gmail.com` on 8 Aug 2012 at 2:34

**Comment by GoogleCodeExporter** [comment]
```
Issue 47 has been merged into this issue.
```

Original comment by `johnpeb@gmail.com` on 9 Aug 2012 at 12:47

**Comment by GoogleCodeExporter** [comment]
```
Issue 50 has been merged into this issue.
```

Original comment by `johnpeb@gmail.com` on 19 Sep 2012 at 12:08
