### ISSUE TITLE
An internal error occurred during: "Updating working directory"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [anterzhang/mercurialeclipse#38]
```
Every time I try to pull from remote server, I get the specificed error.

I'm using eclipse 4.2 (x64) on linux, hg version 2.2.3
Mercurialeclipse 2.0.0.201207050855

By installing stable plugin (1.9.4) the error stops from appearing.



Here follows the error information:

An internal error occurred during: "Updating working directory".

com.aragost.javahg.commands.ExecutionException: no files or directories 
specified; use --all to remerge all files
    at com.aragost.javahg.internals.AbstractCommand.handleReturnCode(AbstractCommand.java:386)
    at com.aragost.javahg.internals.OutputChannelInputStream.findNextOutputChannelBlock(OutputChannelInputStream.java:179)
    at com.aragost.javahg.internals.OutputChannelInputStream.<init>(OutputChannelInputStream.java:78)
    at com.aragost.javahg.internals.Server.runCommand(Server.java:419)
    at com.aragost.javahg.internals.AbstractCommand.launchStream(AbstractCommand.java:176)
    at com.aragost.javahg.internals.AbstractCommand.launchString(AbstractCommand.java:142)
    at com.aragost.javahg.commands.ResolveCommand.execute(ResolveCommand.java:68)
    at com.vectrace.MercurialEclipse.commands.HgResolveClient.autoResolve(HgResolveClient.java:213)
    at com.vectrace.MercurialEclipse.commands.HgUpdateClient.updateWithoutRefreshAndAutoResolve(HgUpdateClient.java:68)
    at com.vectrace.MercurialEclipse.commands.HgUpdateClient.update(HgUpdateClient.java:46)
    at com.vectrace.MercurialEclipse.menu.UpdateJob.run(UpdateJob.java:83)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)


eclipse.buildId=I20120608-1400
java.version=1.7.0_05-icedtea
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=it_IT
Command-line arguments:  -os linux -ws gtk -arch x86_64
```

Original issue reported on code.google.com by `yuri.bug...@gmail.com` on 5 Jul 2012 at 3:55

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. Fixed in next snapshot.
```

Original comment by `johnpeb@gmail.com` on 6 Jul 2012 at 5:30
- Changed state: **Fixed**
