### ISSUE TITLE
eclipse-4.2 cannot start any more

### ISSUE THREAD

**Issue by GoogleCodeExporter** [anterzhang/mercurialeclipse#47]
```
What steps will reproduce the problem?
not sure ... it worked and stopped working.

What is the expected output? What do you see instead?
eclipse does not start up any more but says "an error occured, check 
\workspace\.metadata\.log

org.eclipse.swt.SWTError: Invalid thread access
    at org.eclipse.ui.plugin.AbstractUIPlugin.createImageRegistry(AbstractUIPlugin.java:212)
    at org.eclipse.ui.plugin.AbstractUIPlugin.getImageRegistry(AbstractUIPlugin.java:256)
    at com.vectrace.MercurialEclipse.MercurialEclipsePlugin.getImageDescriptor(MercurialEclipsePlugin.java:326)
    at com.vectrace.MercurialEclipse.views.console.HgConsole.<init>(HgConsole.java:74)
    at com.vectrace.MercurialEclipse.views.console.HgConsoleHolder.init(HgConsoleHolder.java:59)
    at com.vectrace.MercurialEclipse.views.console.HgConsoleHolder.getConsole(HgConsoleHolder.java:135)
    at com.vectrace.MercurialEclipse.DefaultConfiguration.commandInvoked(DefaultConfiguration.java:101)
    at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.logConsoleCommandInvoked(AbstractShellCommand.java:545)
    at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToStream(AbstractShellCommand.java:410)
    at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToBytes(AbstractShellCommand.java:387)
    at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:605)
    at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:601)
    at com.vectrace.MercurialEclipse.commands.HgStatusClient.getStatusWithoutIgnored(HgStatusClient.java:113)
    at com.vectrace.MercurialEclipse.team.cache.MercurialStatusCache.refreshStatus(MercurialStatusCache.java:775)
    at com.vectrace.MercurialEclipse.team.cache.RefreshStatusJob.run(RefreshStatusJob.java:88)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.NullPointerException
    at org.eclipse.ui.internal.WorkbenchPlugin.getSharedImages(WorkbenchPlugin.java:648)
    at org.eclipse.ui.internal.Workbench.getSharedImages(Workbench.java:1315)
    at org.eclipse.ui.plugin.AbstractUIPlugin.imageDescriptorFromPlugin(AbstractUIPlugin.java:670)
    at com.vectrace.MercurialEclipse.MercurialEclipsePlugin.getImageDescriptor(MercurialEclipsePlugin.java:328)
    at com.vectrace.MercurialEclipse.commands.AbstractShellCommand$1.run(AbstractShellCommand.java:109)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)


What version of the product are you using? On what operating system?

com.vectrace.MercurialEclipse_1.9.4.201203270141.jar



```

Original issue reported on code.google.com by `rupert.t...@gmail.com` on 9 Aug 2012 at 7:53
- Merged into: #37

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. This is fixed in 2.0 that should be released next week. 
In the mean time you can run the snapshot available on this update site: 
http://mercurialeclipse.eclipselabs.org.codespot.com/hg.wiki/update_site/snapsho
ts
```

Original comment by `johnpeb@gmail.com` on 9 Aug 2012 at 12:47
- Changed state: **Duplicate**
