### ISSUE TITLE
Internal error during Refresh status (NullPointerException in HgResolveClient.list)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [anterzhang/mercurialeclipse#55]
```
What steps will reproduce the problem?
1. Install MercurialEclipse plugin
2. Link existing project to existing mercurial repo
3. Modify and save a file

What is the expected output? What do you see instead?

Each time a file is saved, or perhaps more frequently, a dialog box pops saying 
"An internal error occurred during: "Refresh status...".

Eclipse log:

!MESSAGE An internal error occurred during: "Refresh status...".
!STACK 0
java.lang.NullPointerException
        at com.vectrace.MercurialEclipse.commands.HgResolveClient.list(HgResolveClient.java:50)
        at com.vectrace.MercurialEclipse.team.cache.MercurialStatusCache.checkForConflict(MercurialStatusCache.java:970)
        at com.vectrace.MercurialEclipse.team.cache.MercurialStatusCache.refreshStatus(MercurialStatusCache.java:917)
        at com.vectrace.MercurialEclipse.team.cache.MercurialStatusCache$ProjectUpdateJob.updateProject(MercurialStatusCache.java:143)
        at com.vectrace.MercurialEclipse.team.cache.MercurialStatusCache$ProjectUpdateJob.run(MercurialStatusCache.java:129)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

What version of the product are you using? On what operating system?

Eclipse Standard/SDK
Version: Kepler Service Release 1
Build id: 20130919-0819
MercurialEclipse    2.1.0.201304290948  mercurialeclipse.feature.group  MercurialEcli
pse project

```

Original issue reported on code.google.com by `nicolas....@intelerad.com` on 31 Jan 2014 at 8:43

**Comment by GoogleCodeExporter** [comment]
```
It seems that it happens when a soft link is added in the repository
```

Original comment by `danielep...@gmail.com` on 28 Feb 2014 at 11:33

**Comment by GoogleCodeExporter** [comment]
```
Thanks for filing the ticket. The main MercurialEclipse bug tracker is: 
https://bitbucket.org/mercurialeclipse/main/wiki/Home
```

Original comment by `johnpeb@gmail.com` on 1 Mar 2014 at 6:23
